# Generated by Django 5.1.3 on 2024-11-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfil_images/'),
        ),
    ]
