# Generated by Django 5.1.3 on 2024-11-30 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portafolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_compra', models.FloatField()),
                ('fecha_compra', models.DateField()),
                ('precio_actual', models.FloatField(default=0.0)),
                ('portafolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones', to='portafolio.portafolio')),
            ],
        ),
    ]
