# Generated by Django 5.1.3 on 2024-11-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccionDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('empresa', models.TextField()),
                ('precio_actual', models.FloatField()),
            ],
        ),
    ]
