# Generated by Django 5.1.3 on 2024-11-30 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_acciondisponible'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acciondisponible',
            old_name='nombre',
            new_name='nombre_accion',
        ),
        migrations.RemoveField(
            model_name='acciondisponible',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='acciondisponible',
            name='precio_actual',
        ),
    ]
