# Generated by Django 5.1.3 on 2024-11-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_rename_nombre_acciondisponible_nombre_accion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acciondisponible',
            name='empresa',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
    ]
