# Generated by Django 5.1.3 on 2024-11-30 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_acciondisponible_empresa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccionDisponible',
        ),
    ]
